import { PrismaService } from '../../database/prisma.service';
import { FreightsService } from '../../freights/freights.service';
import { SessionManagerService } from '../session/session-manager.service';
import { AiContextService } from './ai-context.service';
export declare class FreightQueryToolsService {
    private prisma;
    private freights;
    private sessionManager;
    private aiContext;
    private readonly logger;
    constructor(prisma: PrismaService, freights: FreightsService, sessionManager: SessionManagerService, aiContext: AiContextService);
    private resolveFreightWithAccess;
    private resolveProducerCompanyId;
    private resolveCompanyType;
    private storePendingSelection;
    toolListFreights(synUser: any, input: any, session: any): Promise<string>;
    toolSummarizeFreights(synUser: any, input: any): Promise<string>;
    toolGetFreightDetail(input: any, user: any, session?: any): Promise<string>;
    private getQuickActionButtons;
    toolGetDashboard(user: any): Promise<string>;
    toolFreightHistory(input: any, user: any): Promise<string>;
    toolListDocuments(input: any, user: any): Promise<string>;
    toolSearchPlants(input: any, user: any, session: any): Promise<string>;
    toolListLots(user: any, session: any, input?: any): Promise<string>;
    toolListFields(user: any, session: any): Promise<string>;
    toolSearchFields(input: any, user: any): Promise<string>;
    toolSearchLots(input: any, user: any): Promise<string>;
    toolRenameDocument(input: any, user: any): Promise<string>;
    toolGenerateShareLinkWithDetails(input: any, user: any): Promise<string>;
}
import { ConfigService } from '@nestjs/config';
import { FieldsService } from '../../fields/fields.service';
import { TrucksService } from '../../trucks/trucks.controller';
import { AdminService } from '../../admin/admin.controller';
import { WhatsAppService } from '../../whatsapp/whatsapp.service';
import { OcrService } from '../../ocr/ocr.service';
import { LocationToolsService } from './location-tools.service';
export declare class FreightActionToolsService {
    private config;
    private prisma;
    private freights;
    private fieldsService;
    private ocrService;
    private sessionManager;
    private aiContext;
    private locationTools;
    private trucksService;
    private adminService;
    private wa;
    private readonly logger;
    constructor(config: ConfigService, prisma: PrismaService, freights: FreightsService, fieldsService: FieldsService, ocrService: OcrService, sessionManager: SessionManagerService, aiContext: AiContextService, locationTools: LocationToolsService, trucksService: TrucksService, adminService: AdminService, wa: WhatsAppService);
    toolUpdateFreight(input: any, user: any, session: any): Promise<string>;
    toolDuplicateFreight(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolPrepareFreight(input: any, user: any, session: any): Promise<string>;
    toolConfirmCreateFreight(user: any, synUser: any, session: any): Promise<string>;
    toolConfirmAction(user: any, synUser: any, session: any): Promise<string>;
    toolAcceptFreight(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolRejectFreight(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolStartFreight(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolConfirmLoaded(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolConfirmFinished(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolCancelFreight(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolCreateField(input: any, user: any, session: any): Promise<string>;
    toolCreateLot(input: any, user: any, session: any): Promise<string>;
    toolUpdateField(input: any, user: any, session: any): Promise<string>;
    toolUpdateLot(input: any, user: any, session: any): Promise<string>;
    toolReactivateUser(input: any, user: any, session: any): Promise<string>;
    toolAttachDocument(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolAuthorizeFreight(input: any, user: any, session: any): Promise<string>;
    toolApprovePendingChange(input: any, user: any, session: any): Promise<string>;
    toolRejectPendingChange(input: any, user: any, session: any): Promise<string>;
    toolRespondTrip(input: any, user: any, session: any): Promise<string>;
    toolStartTrip(input: any, user: any, session: any): Promise<string>;
    toolConfirmTripLoaded(input: any, user: any, session: any): Promise<string>;
    toolConfirmTripFinished(input: any, user: any, session: any): Promise<string>;
    toolDeleteDocument(input: any, user: any, session: any): Promise<string>;
    toolSaveOcrData(input: any, user: any, session: any): Promise<string>;
    toolOcrAnalyze(input: any, user: any, session: any): Promise<string>;
}
export declare class TransportToolsService {
    private prisma;
    private trucksService;
    private freights;
    private sessionManager;
    private aiContext;
    private readonly logger;
    constructor(prisma: PrismaService, trucksService: TrucksService, freights: FreightsService, sessionManager: SessionManagerService, aiContext: AiContextService);
    private buildSyntheticUser;
    private resolveCompanyType;
    private resolvePlantCompanyId;
    private isCallerAdminForCompany;
    private resolveFreightWithAccess;
    private stageAction;
    private storePendingSelection;
    private resolveAssignment;
    toolListTransporters(input: any, user: any, session: any): Promise<string>;
    toolAssignTransporter(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolAssignTruckToTrip(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolAssignTruckToFreight(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolAssignMultiTrucks(input: any, user: any, session: any): Promise<string>;
    toolCancelAssignment(input: any, user: any, session: any): Promise<string>;
    toolUpdateAssignment(input: any, user: any, session: any): Promise<string>;
    toolListTrucks(user: any, session: any): Promise<string>;
    toolCreateTruck(input: any, user: any, session: any): Promise<string>;
    toolUpdateTruck(input: any, user: any, session: any): Promise<string>;
    toolDeactivateTruck(input: any, user: any, session: any): Promise<string>;
    toolListDrivers(user: any, session: any): Promise<string>;
    toolCreateDriver(input: any, user: any, session: any): Promise<string>;
    toolDeactivateDriver(input: any, user: any, session: any): Promise<string>;
    toolViewDriverQueue(input: any, user: any): Promise<string>;
    toolReorderDriverQueue(input: any, user: any, session: any): Promise<string>;
    toolAssignExternalTruck(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolAssignMixedTrucks(input: any, user: any, synUser: any, session: any): Promise<string>;
    toolEditExternalAssignment(input: any, user: any, synUser: any, session: any): Promise<string>;
}
import { AssignmentSuggestionsService } from '../../freights/assignment-suggestions.service';
export declare class AdminToolsService {
    private config;
    private prisma;
    private adminService;
    private assignmentSuggestions;
    private sessionManager;
    private aiContext;
    private readonly logger;
    constructor(config: ConfigService, prisma: PrismaService, adminService: AdminService, assignmentSuggestions: AssignmentSuggestionsService, sessionManager: SessionManagerService, aiContext: AiContextService);
    private resolveCompanyType;
    private resolveProducerCompanyId;
    private resolvePlantCompanyId;
    private isCallerAdminForCompany;
    private stageAction;
    private storePendingSelection;
    toolGetUserProfile(user: any): string;
    toolCreateUser(input: any, user: any, session: any): Promise<string>;
    toolListCompanyUsers(user: any, session: any): Promise<string>;
    toolUpdateUserRole(input: any, user: any, session: any): Promise<string>;
    toolDeactivateUser(input: any, user: any, session: any): Promise<string>;
    toolReactivateUser(input: any, user: any, session: any): Promise<string>;
    toolUpdateProfile(input: any, user: any, session: any): Promise<string>;
    toolUpdateUserAdmin(input: any, user: any, session: any): Promise<string>;
    toolSwitchCompany(input: any, user: any, session: any): Promise<string>;
    toolUpdateCompany(input: any, user: any, session: any): Promise<string>;
    toolListEnabledPlants(user: any): Promise<string>;
    toolListEnabledProducers(user: any): Promise<string>;
    toolGrantProducerAccess(input: any, user: any, session: any): Promise<string>;
    toolRevokeProducerAccess(input: any, user: any, session: any): Promise<string>;
    toolListBranches(user: any): Promise<string>;
    toolCreateBranch(input: any, user: any, session: any): Promise<string>;
    toolUpdateBranch(input: any, user: any, session: any): Promise<string>;
    toolDeleteBranch(input: any, user: any, session: any): Promise<string>;
    toolGetAssignmentSuggestions(input: any, user: any): Promise<string>;
}
export declare class LocationToolsService {
    private config;
    private prisma;
    private wa;
    private sessionManager;
    private aiContext;
    private readonly logger;
    _requestLocationCooldowns: Map<string, number>;
    cleanupCooldowns(): void;
    constructor(config: ConfigService, prisma: PrismaService, wa: WhatsAppService, sessionManager: SessionManagerService, aiContext: AiContextService);
    private fetchFreightAndEnsureToken;
    toolNavigateApp(input: any, session: any): string;
    toolGenerateLocationLink(input: any, session: any): string;
    toolGenerateTrackingLink(input: any, user: any): Promise<string>;
    toolGenerateMapLink(input: any): string;
    toolGenerateReportLink(input: any, user: any): Promise<string>;
    toolGenerateSharedLink(input: any, user: any): Promise<string>;
    toolGenerateDailyMapLink(user: any): Promise<string>;
    toolShareLiveLocation(input: any, user: any): Promise<string>;
    toolViewLiveLocations(input: any, user: any): Promise<string>;
    toolRequestLocation(input: any, user: any): Promise<string>;
    toolGenerateBatchReportLink(input: any, _user: any): Promise<string>;
    sendPostStartTrackingMessages(freightId: string, code: string, triggerUser: any): Promise<void>;
}
export declare class AiContextService {
    private prisma;
    private readonly logger;
    constructor(prisma: PrismaService);
    resolveFreightWithAccess(code: string, user: any): Promise<{
        freight?: any;
        error?: string;
    }>;
    findFreightByCode(code: string): Promise<any>;
    findFreightsByCodePattern(pattern: string, userCompanyIds: string[], userId: string): Promise<any>;
    resolveAssignment(code: string, assignmentId: string | undefined, user: any, session?: any): Promise<{
        freight?: any;
        assignment?: any;
        error?: string;
    }>;
    resolveCompanyType(user: any): string;
    resolveProducerCompanyIdForCompany(user: any, targetCompanyId: string): string | null;
    resolveProducerCompanyId(user: any): string | null;
    resolvePlantCompanyId(user: any): string | null;
    isCallerAdminForCompany(user: any, companyId?: string): boolean;
    canAccessCompany(user: any, synUser: any, companyId: string): boolean;
    buildSyntheticUser(dbUser: any): any;
}
import { OnModuleDestroy } from '@nestjs/common';
import { ResponseFormatterService } from './response/response-formatter.service';
import { PromptBuilderService } from './prompt/prompt-builder.service';
import { IntentRouterService } from './routing/intent-router.service';
import { AdminToolsService } from './tools/admin-tools.service';
import { TransportToolsService } from './tools/transport-tools.service';
import { FreightQueryToolsService } from './tools/freight-query-tools.service';
import { FreightActionToolsService } from './tools/freight-action-tools.service';
import { MessageInterceptorService } from './interceptor/message-interceptor.service';
export declare class AiService implements OnModuleDestroy {
    private config;
    private prisma;
    private freights;
    private wa;
    private fieldsService;
    private trucksService;
    private adminService;
    private ocrService;
    private assignmentSuggestions;
    private responseFormatter;
    private sessionManager;
    private promptBuilder;
    private intentRouter;
    private aiContext;
    private locationTools;
    private adminTools;
    private transportTools;
    private freightQueryTools;
    private freightActionTools;
    private interceptor;
    private readonly logger;
    private client;
    get _chatSideEffects(): Map<string, Record<string, any>>;
    private _chatLocks;
    private rateCleanupTimer;
    constructor(config: ConfigService, prisma: PrismaService, freights: FreightsService, wa: WhatsAppService, fieldsService: FieldsService, trucksService: TrucksService, adminService: AdminService, ocrService: OcrService, assignmentSuggestions: AssignmentSuggestionsService, responseFormatter: ResponseFormatterService, sessionManager: SessionManagerService, promptBuilder: PromptBuilderService, intentRouter: IntentRouterService, aiContext: AiContextService, locationTools: LocationToolsService, adminTools: AdminToolsService, transportTools: TransportToolsService, freightQueryTools: FreightQueryToolsService, freightActionTools: FreightActionToolsService, interceptor: MessageInterceptorService);
    private _promptCache;
    private readonly PROMPT_CACHE_TTL;
    private _sonnetRetried;
    onModuleDestroy(): void;
    isEnabled(): boolean;
    private selectModel;
    chat(phone: string, userMessage: string, user: any, session: any, onDelta?: (chunk: string, start?: boolean) => void): Promise<{
        text: string;
        buttons?: Array<{
            id: string;
            title: string;
        }>;
        navigate?: {
            screen: string;
            freightId?: string;
        };
    }>;
    private sanitizeForPrompt;
    private buildSystemPrompt;
    private getFilteredTools;
    private readonly tools;
    private static readonly ACTION_TOOLS;
    private static readonly CONSULTA_BLOCKED_TOOLS;
    private resolveUserPlantAccess;
    private isGlobalConsulta;
    private static readonly SEARCH_TOOLS;
    private executeTool;
    private _executeToolInner;
    private executeFleetTool;
}
export declare class SessionManagerService {
    private _chatSideEffects;
    getChatSideEffectsMap(): Map<string, Record<string, any>>;
    getSideEffects(sessionId: string): Record<string, any>;
    setSideEffects(sessionId: string, effects: Record<string, any>): void;
    deleteSideEffects(sessionId: string): void;
    cleanStaleSideEffects(): void;
    updateActiveContext(sessionId: string, context: Record<string, any>): void;
    storePendingSelection(sessionId: string, items: {
        id: string;
        title: string;
        description?: string;
    }[], config: {
        headerText: string;
        listButtonLabel: string;
        sectionTitle: string;
    }, purpose: string, extraJson?: Record<string, any>): string;
    stageAction(sessionId: string, tool: string, params: Record<string, any>, summary: string, user?: any): string;
    smartTrimHistory(messages: any[]): any[];
}
export declare class ResponseFormatterService {
    preprocessMessage(text: string): string;
    validateResponse(text: string, isWeb?: boolean): string;
}
export declare function resolveCompanyTypes(company: any): string[];
export declare function resolveActiveRole(user: any): {
    isChofer: boolean;
    isAdmin: boolean;
    userRole: string;
};
export declare function isProducerMembership(m: any): boolean;
export declare function hasType(companyType: string, type: string): boolean;
export declare function sanitizeForPrompt(s: string): string;
export declare function aiBuildSyntheticUser(dbUser: any): any;
export declare const MAX_HISTORY = 15;
export declare const MAX_TOOL_LOOPS = 5;
export declare const AI_SESSION_TIMEOUT_MIN = 60;
export declare const APP_URL: string;
export declare const OWN_FLEET_SHORTCUT = "own_fleet";
export declare const MODELS: {
    readonly haiku: "claude-haiku-4-5-20251001";
    readonly sonnet: "claude-sonnet-4-6";
};
export type ModelTier = keyof typeof MODELS;
export declare const MODEL_ID: "claude-sonnet-4-6";
export declare const MODEL_ID_FAST: "claude-haiku-4-5-20251001";
export declare const MODEL_TEMPERATURE = 0.4;
export declare const MODEL_MAX_TOKENS = 1024;
export declare const HAIKU_MAX_TOKENS = 600;
export declare const SONNET_MAX_TOKENS = 2048;
export declare const MAX_RESPONSE_CHARS = 1600;
export declare const WEB_MAX_RESPONSE_CHARS = 3000;
export declare const STALE_SESSION_MIN = 10;
export declare const URUGUAY_UTC_OFFSET_MS: number;
export declare const FREIGHT_STATUS_LABELS: Record<string, string>;
export declare const FREIGHT_STATUS_SHORT: Record<string, string>;
export declare const AUDIO_FILLERS: RegExp;
export declare const AI_RATE_LIMIT_WINDOW_MS: number;
export declare const AI_RATE_LIMIT_MAX = 20;
export interface AiToolDefinition {
    name: string;
    description: string;
    input_schema: {
        type: 'object';
        properties: Record<string, any>;
        required: string[];
    };
}
export declare const AI_TOOL_DEFINITIONS: AiToolDefinition[];
export declare class PromptBuilderService {
    private prisma;
    private readonly logger;
    constructor(prisma: PrismaService);
    private resolveProducerCompanyId;
    build(user: any, companyType: string, isWeb?: boolean, plantAccessMap?: Map<string, string>): Promise<string>;
}
