// =====================================================================
// TOLVINK — Complete AI Tool Definitions (reduced set ~57 tools)
// Uses Anthropic input_schema format — converted to Gemini at runtime
// =====================================================================

export interface AiToolDefinition {
  name: string;
  description: string;
  input_schema: {
    type: 'object';
    properties: Record<string, any>;
    required: string[];
  };
}

export const ALL_TOOL_DEFINITIONS: AiToolDefinition[] = [
  // ======================== CONSULTAS DE FLETES ========================
  { name: 'list_freights', description: 'Lista fletes como menu interactivo para seleccion individual. Para resumen/conteo usar summarize_freights.', input_schema: { type: 'object', properties: { status: { type: 'string', enum: ['pending_assignment','assigned','accepted','in_progress','loaded','finished','canceled'], description: 'Filtrar por estado' }, dateFrom: { type: 'string', description: 'Fecha desde (YYYY-MM-DD)' }, dateTo: { type: 'string', description: 'Fecha hasta (YYYY-MM-DD)' }, grain: { type: 'string', description: 'Filtrar por grano' } }, required: [] } },
  { name: 'get_freight_detail', description: 'Detalle de flete por codigo. Incluye estado, datos, asignaciones, historial y mapLink.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' } }, required: ['code'] } },
  { name: 'summarize_freights', description: 'Resumen analitico de fletes en texto para agrupar, contar o analizar.', input_schema: { type: 'object', properties: { status: { type: 'string', enum: ['pending_assignment','assigned','accepted','in_progress','loaded','finished','canceled'], description: 'Filtrar por estado' }, groupBy: { type: 'string', enum: ['transporter','status','grain','destination','origin'], description: 'Agrupar por criterio' }, dateFrom: { type: 'string', description: 'Fecha desde (YYYY-MM-DD)' }, dateTo: { type: 'string', description: 'Fecha hasta (YYYY-MM-DD)' }, grain: { type: 'string', description: 'Filtrar por grano' }, transporterName: { type: 'string', description: 'Filtrar por transportista (fuzzy)' } }, required: [] } },
  { name: 'get_dashboard', description: 'Resumen ejecutivo: fletes por estado, toneladas del mes, completados vs cancelados.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'freight_history', description: 'Historial de un flete: quien hizo que y cuando.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' } }, required: ['code'] } },
  // ======================== CREACION DE FLETES ========================
  { name: 'prepare_freight', description: 'Prepara flete completo (no lo crea). Incluir TODOS los datos de transporte aqui para que se asignen automaticamente al confirmar. Para propio: truckId+driverId. Para externo: externalPlate (empresa/chofer opcionales). Para multi-camion mixto: usar trucks[]. Confirmar con confirm_create_freight.', input_schema: { type: 'object', properties: { grain: { type: 'string', enum: ['Soja','Maiz','Trigo','Girasol','Sorgo','Cebada','Otros'], description: 'Tipo de grano' }, tons: { type: 'number', description: 'Toneladas (opcional)' }, truckCount: { type: 'number', description: 'Cantidad de camiones. OBLIGATORIO.' }, loadDate: { type: 'string', description: 'Fecha de carga (YYYY-MM-DD)' }, loadTime: { type: 'string', description: 'Hora de carga (HH:mm)' }, useOwnFleet: { type: 'boolean', description: 'true=flota propia, false=planta asigna' }, destPlantId: { type: 'string', description: 'UUID planta destino' }, destName: { type: 'string', description: 'Nombre planta, auto-resuelve con fuzzy' }, branchId: { type: 'string', description: 'UUID sucursal' }, customDestName: { type: 'string', description: 'Nombre del destino personalizado (si no va a planta)' }, customDestLat: { type: 'number', description: 'Latitud destino custom' }, customDestLng: { type: 'number', description: 'Longitud destino custom' }, originLotId: { type: 'string', description: 'UUID lote origen' }, originName: { type: 'string', description: 'Nombre campo/lote, auto-resuelve' }, customOriginName: { type: 'string', description: 'Nombre origen personalizado' }, customOriginLat: { type: 'number', description: 'Latitud origen custom' }, customOriginLng: { type: 'number', description: 'Longitud origen custom' }, truckId: { type: 'string', description: 'UUID camion propio (de list_trucks)' }, driverId: { type: 'string', description: 'UUID chofer o "self" para el usuario actual' }, externalPlate: { type: 'string', description: 'Patente del camion externo (ej: OAD2334). Se asigna automaticamente al confirmar.' }, externalCompanyName: { type: 'string', description: 'Empresa del externo (opcional, NUNCA preguntar)' }, externalDriverName: { type: 'string', description: 'Chofer del externo (opcional, NUNCA preguntar)' }, trucks: { type: 'array', description: 'Para multi-camion mixto: array de camiones. Cada uno con {isExternal, plate, truckId, driverId, externalCompanyName, externalDriverName, transportCompanyId}', items: { type: 'object', properties: { isExternal: { type: 'boolean' }, plate: { type: 'string' }, truckId: { type: 'string' }, driverId: { type: 'string' }, externalCompanyName: { type: 'string' }, externalDriverName: { type: 'string' }, transportCompanyId: { type: 'string' } } } }, notes: { type: 'string', description: 'Notas adicionales' } }, required: ['grain','loadDate','truckCount'] } },
  { name: 'confirm_create_freight', description: 'Crea el flete preparado. Llamar solo cuando el usuario confirma.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'duplicate_freight', description: 'Duplica flete existente con nueva fecha.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete original' }, loadDate: { type: 'string', description: 'Fecha de carga (YYYY-MM-DD)' }, loadTime: { type: 'string', description: 'Hora de carga (HH:mm)' } }, required: ['code','loadDate'] } },
  { name: 'update_freight', description: 'Modifica flete: fecha, hora, notas, destino, camion, chofer, truckCount, flota propia.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, loadDate: { type: 'string', description: 'Nueva fecha (YYYY-MM-DD)' }, loadTime: { type: 'string', description: 'Nueva hora (HH:mm)' }, notes: { type: 'string', description: 'Nuevas notas' }, useOwnFleet: { type: 'boolean', description: 'Cambiar a flota propia' }, destPlantId: { type: 'string', description: 'UUID nueva planta destino' }, truckId: { type: 'string', description: 'UUID camion propio' }, driverId: { type: 'string', description: 'UUID chofer o "self"' }, truckCount: { type: 'number', description: 'Nueva cantidad de camiones' } }, required: ['code'] } },
  // ======================== CONFIRMACION GENERICA ========================
  { name: 'confirm_action', description: 'Ejecuta accion previamente preparada cuando el usuario confirma.', input_schema: { type: 'object', properties: {}, required: [] } },
  // ======================== ACCIONES DE FLETE ========================
  { name: 'accept_freight', description: 'Acepta flete asignado. Solo estado "assigned".', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' } }, required: ['code'] } },
  { name: 'reject_freight', description: 'Rechaza flete asignado. Requiere motivo.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, reason: { type: 'string', description: 'Motivo del rechazo' } }, required: ['code','reason'] } },
  { name: 'start_freight', description: 'Inicia viaje de flete aceptado.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' } }, required: ['code'] } },
  { name: 'confirm_loaded', description: 'Confirma carga del flete. Toneladas opcionales — solo registrar si el usuario las menciona, NUNCA preguntar.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, tons: { type: 'number', description: 'Toneladas reales cargadas (opcional)' } }, required: ['code'] } },
  { name: 'confirm_finished', description: 'Confirma entrega/recepcion.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' } }, required: ['code'] } },
  { name: 'cancel_freight', description: 'Cancela flete. Requiere motivo.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, reason: { type: 'string', description: 'Motivo' } }, required: ['code','reason'] } },
  { name: 'authorize_freight', description: 'Autoriza flete con flota propia. Solo plantas.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' } }, required: ['code'] } },
  // ======================== VIAJES MULTI-CAMION ========================
  { name: 'respond_trip', description: 'Acepta o rechaza viaje en flete multi-camion.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, assignmentId: { type: 'string', description: 'UUID asignacion' }, action: { type: 'string', enum: ['accepted','rejected'], description: 'Accion' }, reason: { type: 'string', description: 'Motivo (si rejected)' } }, required: ['code','action'] } },
  { name: 'start_trip', description: 'Inicia viaje especifico de flete multi-camion.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, assignmentId: { type: 'string', description: 'UUID asignacion' } }, required: ['code'] } },
  { name: 'confirm_trip_loaded', description: 'Confirma carga de viaje especifico.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, assignmentId: { type: 'string', description: 'UUID asignacion' }, loadedTons: { type: 'number', description: 'Toneladas cargadas' } }, required: ['code'] } },
  { name: 'confirm_trip_finished', description: 'Confirma entrega de viaje especifico.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, assignmentId: { type: 'string', description: 'UUID asignacion' } }, required: ['code'] } },
  // ======================== ASIGNACION DE TRANSPORTE ========================
  { name: 'list_transporters', description: 'Lista transportistas disponibles.', input_schema: { type: 'object', properties: { query: { type: 'string', description: 'Filtrar por nombre (fuzzy)' } }, required: [] } },
  { name: 'assign_transporter', description: 'Asigna transportista a flete. Usar "own_fleet" para flota propia.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, transporterCompanyId: { type: 'string', description: 'UUID empresa o "own_fleet"' }, truckId: { type: 'string', description: 'UUID camion' }, driverId: { type: 'string', description: 'UUID chofer' } }, required: ['code','transporterCompanyId'] } },
  { name: 'assign_truck_to_trip', description: 'Asigna o cambia camion en viaje existente.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, truckId: { type: 'string', description: 'UUID del camion' }, driverId: { type: 'string', description: 'UUID chofer' } }, required: ['code','truckId'] } },
  { name: 'assign_truck_to_freight', description: 'Asigna camion adicional a flete multi-camion.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, transporterCompanyId: { type: 'string', description: 'UUID empresa o "own_fleet"' }, truckId: { type: 'string', description: 'UUID camion' }, driverId: { type: 'string', description: 'UUID chofer' }, tons: { type: 'number', description: 'Toneladas para este viaje' } }, required: ['code','transporterCompanyId'] } },
  { name: 'cancel_assignment', description: 'Cancela asignacion de camion. Requiere motivo.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, assignmentId: { type: 'string', description: 'UUID asignacion' }, reason: { type: 'string', description: 'Motivo' } }, required: ['code','reason'] } },
  { name: 'update_assignment', description: 'Edita asignacion existente.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, assignmentId: { type: 'string', description: 'UUID asignacion' }, transporterCompanyId: { type: 'string' }, truckId: { type: 'string' }, driverId: { type: 'string' }, tons: { type: 'number' } }, required: ['code'] } },
  { name: 'assign_external_truck', description: 'Asigna camion de terceros a flete.', input_schema: { type: 'object', properties: { code: { type: 'string' }, plate: { type: 'string' }, externalCompanyName: { type: 'string', description: 'Empresa del camion externo. Solo si el usuario lo menciona espontaneamente — NUNCA preguntar.' }, externalDriverName: { type: 'string', description: 'Chofer del camion externo. Solo si el usuario lo menciona espontaneamente — NUNCA preguntar.' } }, required: ['code','plate'] } },
  { name: 'edit_external_assignment', description: 'Edita datos de camion externo asignado.', input_schema: { type: 'object', properties: { code: { type: 'string' }, assignmentId: { type: 'string' }, plate: { type: 'string' }, externalCompanyName: { type: 'string', description: 'Solo si el usuario lo menciona — NUNCA preguntar.' }, externalDriverName: { type: 'string', description: 'Solo si el usuario lo menciona — NUNCA preguntar.' } }, required: ['code'] } },
  // ======================== CAMPOS Y LOTES ========================
  { name: 'search_plants', description: 'Busca plantas destino por nombre (fuzzy).', input_schema: { type: 'object', properties: { query: { type: 'string', description: 'Nombre parcial de planta' } }, required: ['query'] } },
  { name: 'list_fields', description: 'Lista campos del productor.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'list_lots', description: 'Lista lotes del productor. Puede filtrar por campo.', input_schema: { type: 'object', properties: { fieldId: { type: 'string', description: 'UUID campo' } }, required: [] } },
  { name: 'search_fields', description: 'Busca campos por nombre (fuzzy).', input_schema: { type: 'object', properties: { query: { type: 'string', description: 'Nombre del campo' } }, required: ['query'] } },
  { name: 'search_lots', description: 'Busca lotes por nombre (fuzzy).', input_schema: { type: 'object', properties: { query: { type: 'string', description: 'Nombre del lote' }, fieldId: { type: 'string', description: 'UUID campo' } }, required: ['query'] } },
  // ======================== CAMIONES Y CHOFERES ========================
  { name: 'list_trucks', description: 'Lista camiones de la empresa.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'list_drivers', description: 'Lista choferes de la empresa.', input_schema: { type: 'object', properties: {}, required: [] } },
  // ======================== DOCUMENTOS ========================
  { name: 'attach_document', description: 'Adjunta imagen/documento pendiente a un flete.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete' }, step: { type: 'string', enum: ['request','assignment','load_confirmation','delivery_confirmation','cancellation'] } }, required: ['code'] } },
  { name: 'list_documents', description: 'Lista documentos adjuntos de un flete.', input_schema: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } },
  { name: 'delete_document', description: 'Elimina documento de un flete.', input_schema: { type: 'object', properties: { code: { type: 'string' }, documentId: { type: 'string' } }, required: ['code','documentId'] } },
  { name: 'rename_document', description: 'Renombra documento adjunto a un flete.', input_schema: { type: 'object', properties: { code: { type: 'string' }, documentId: { type: 'string' }, newName: { type: 'string' } }, required: ['code','documentId','newName'] } },
  // ======================== UBICACIONES Y MAPAS ========================
  { name: 'generate_tracking_link', description: 'Link publico para rastrear flete.', input_schema: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } },
  { name: 'generate_report_link', description: 'Link para descargar PDF de un flete.', input_schema: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } },
  { name: 'share_live_location', description: 'Link para compartir ubicacion en vivo.', input_schema: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } },
  { name: 'view_live_locations', description: 'Link para ver ubicaciones en vivo.', input_schema: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } },
  // ======================== USUARIO Y EMPRESA ========================
  { name: 'get_user_profile', description: 'Datos del perfil del usuario.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'update_profile', description: 'Modifica perfil del usuario actual.', input_schema: { type: 'object', properties: { name: { type: 'string' }, email: { type: 'string' }, phone: { type: 'string' } }, required: [] } },
  { name: 'switch_company', description: 'Cambia empresa activa.', input_schema: { type: 'object', properties: { companyId: { type: 'string' } }, required: [] } },
  // ======================== ACCESO PLANTA-PRODUCTOR ========================
  { name: 'list_enabled_plants', description: 'Lista plantas habilitadas para el productor.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'list_enabled_producers', description: 'Lista productores habilitados en la planta.', input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'grant_producer_access', description: 'Habilita productor para operar con la planta.', input_schema: { type: 'object', properties: { producerCompanyId: { type: 'string' }, producerUserId: { type: 'string' } }, required: ['producerCompanyId'] } },
  { name: 'revoke_producer_access', description: 'Revoca acceso de productor.', input_schema: { type: 'object', properties: { accessId: { type: 'string' } }, required: ['accessId'] } },
  // ======================== AUTONOMOUS DRIVER ========================
  { name: 'prepare_autonomous_freight', description: 'Prepara flete autonomo para chofer independiente. El flete nace en estado "loaded" (ya cargado). Usar confirm_action para confirmar.', input_schema: { type: 'object', properties: { origin: { type: 'string', description: 'Campo/lote de origen o nombre libre' }, destination: { type: 'string', description: 'Planta destino o nombre libre' }, grain: { type: 'string', description: 'Tipo de grano (texto libre, se normaliza)' }, weightKg: { type: 'number', description: 'Peso en kg' }, notes: { type: 'string', description: 'Notas adicionales' }, fieldId: { type: 'string', description: 'UUID campo (si se resolvio con search_fields)' }, originLotId: { type: 'string', description: 'UUID lote (si se resolvio con search_lots)' }, destPlantId: { type: 'string', description: 'UUID planta (si se resolvio con search_plants)' }, branchId: { type: 'string', description: 'UUID sucursal destino' } }, required: ['origin', 'destination', 'grain', 'weightKg'] } },
  { name: 'finish_autonomous_freight', description: 'Finaliza flete autonomo. Si no se pasa code, auto-detecta el flete activo.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete (opcional, auto-detecta si hay uno solo activo)' }, destinationWeightKg: { type: 'number', description: 'Peso en destino (kg, del ticket de balanza)' }, notes: { type: 'string', description: 'Observaciones de entrega' } }, required: [] } },
  { name: 'register_plant_arrival', description: 'Registra llegada a planta del chofer autonomo. Si no se pasa code, auto-detecta el flete activo.', input_schema: { type: 'object', properties: { code: { type: 'string', description: 'Codigo del flete (opcional, auto-detecta si hay uno solo activo)' } }, required: [] } },
];
