import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const templates = [
    // ── JOHN DEERE TRACTORS ──
    { brand: 'John Deere', series: 'Serie 6J', model: '6110J', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech 4045', enginePower: '106 hp', engineDisplacement: '4.5L', transmissionType: 'PowerQuad Plus 16x16', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 6J', model: '6135J', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech 4045', enginePower: '135 hp', engineDisplacement: '4.5L', transmissionType: 'PowrReverser 12x12', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 6J', model: '6155J', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech 4045', enginePower: '155 hp', engineDisplacement: '4.5L', transmissionType: 'CommandQuad 20x20', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 6R', model: '6195R', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6068', enginePower: '195 hp', engineDisplacement: '6.8L', transmissionType: 'AutoPowr IVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 6R', model: '6215R', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6068', enginePower: '215 hp', engineDisplacement: '6.8L', transmissionType: 'AutoPowr IVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 7R', model: '7230R', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6068', enginePower: '230 hp', engineDisplacement: '6.8L', transmissionType: 'e23 PowerShift', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 8R', model: '8245R', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6068', enginePower: '245 hp', engineDisplacement: '6.8L', transmissionType: 'e23 PowerShift', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 8R', model: '8295R', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6090', enginePower: '295 hp', engineDisplacement: '8.1L', transmissionType: 'e23 PowerShift', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 8R', model: '8345R', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6090', enginePower: '345 hp', engineDisplacement: '8.1L', transmissionType: 'e23 PowerShift', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'John Deere', series: 'Serie 8R', model: '8R 410', machineType: 'tractor', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6090', enginePower: '410 hp', engineDisplacement: '8.1L', transmissionType: 'e23 PowerShift', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    // ── CASE IH TRACTORS ──
    { brand: 'Case IH', series: 'Farmall', model: 'Farmall 80', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'F5C', enginePower: '80 hp', engineDisplacement: '3.4L', transmissionType: 'Sincronizada 8x8', fuelType: 'Diésel', hydraulicSystem: 'Circuito abierto', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Case IH', series: 'Maxxum', model: 'Maxxum 135', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'NEF 4.5', enginePower: '135 hp', engineDisplacement: '4.5L', transmissionType: 'ActiveDrive 8 Semi-Powershift', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Case IH', series: 'Puma', model: 'Puma 185', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'NEF 6.7', enginePower: '185 hp', engineDisplacement: '6.7L', transmissionType: 'CVXDrive CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Case IH', series: 'Magnum', model: 'Magnum 310', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'Cursor 9', enginePower: '310 hp', engineDisplacement: '8.7L', transmissionType: 'Full Powershift 18x4', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1500 } },
    { brand: 'Case IH', series: 'Magnum', model: 'Magnum 380', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'Cursor 9', enginePower: '380 hp', engineDisplacement: '8.7L', transmissionType: 'CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1500 } },
    // ── NEW HOLLAND TRACTORS ──
    { brand: 'New Holland', series: 'T6', model: 'T6.160', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'NEF 6.7', enginePower: '160 hp', engineDisplacement: '6.7L', transmissionType: 'ElectroCommand 16x16', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'New Holland', series: 'T7', model: 'T7.245', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'NEF 6.7', enginePower: '245 hp', engineDisplacement: '6.7L', transmissionType: 'AutoCommand CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'New Holland', series: 'T7', model: 'T7.290', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'NEF 6.7', enginePower: '290 hp', engineDisplacement: '6.7L', transmissionType: 'AutoCommand CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'New Holland', series: 'T8', model: 'T8.380', machineType: 'tractor', engineBrand: 'FPT', engineModel: 'Cursor 9', enginePower: '380 hp', engineDisplacement: '8.7L', transmissionType: 'CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1500 } },
    // ── MASSEY FERGUSON TRACTORS ──
    { brand: 'Massey Ferguson', series: 'MF 4700', model: 'MF 4709', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '33 AWI', enginePower: '92 hp', engineDisplacement: '3.3L', transmissionType: 'Sincronizada 12x12', fuelType: 'Diésel', hydraulicSystem: 'Circuito abierto', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Massey Ferguson', series: 'MF 6700', model: 'MF 6711', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '44 AWI', enginePower: '110 hp', engineDisplacement: '4.4L', transmissionType: 'Dyna-4 16x16', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Massey Ferguson', series: 'MF 7700', model: 'MF 7719', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '66 AWI', enginePower: '190 hp', engineDisplacement: '6.6L', transmissionType: 'Dyna-VT CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Massey Ferguson', series: 'MF 8700', model: 'MF 8727', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '84 AWI', enginePower: '270 hp', engineDisplacement: '8.4L', transmissionType: 'Dyna-VT CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1500 } },
    // ── VALTRA TRACTORS ──
    { brand: 'Valtra', series: 'Serie A', model: 'A114', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '44 AWI', enginePower: '114 hp', engineDisplacement: '4.4L', transmissionType: 'HiTech 16x16', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Valtra', series: 'Serie BH', model: 'BH174', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '66 AWI', enginePower: '174 hp', engineDisplacement: '6.6L', transmissionType: 'HiTech 16x16', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    { brand: 'Valtra', series: 'Serie BT', model: 'BT210', machineType: 'tractor', engineBrand: 'AGCO Power', engineModel: '74 AWI', enginePower: '210 hp', engineDisplacement: '7.4L', transmissionType: 'Direct CVT', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado sensible a la carga', maintenanceIntervals: { oilChange: 250, filters: 500, majorService: 1000 } },
    // ── JOHN DEERE HARVESTERS ──
    { brand: 'John Deere', series: 'Serie S', model: 'S660', machineType: 'harvester', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6090', enginePower: '333 hp', engineDisplacement: '9.0L', transmissionType: 'Hydrostática ProDrive', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    { brand: 'John Deere', series: 'Serie S', model: 'S770', machineType: 'harvester', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6135', enginePower: '473 hp', engineDisplacement: '13.5L', transmissionType: 'Hydrostática ProDrive', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    { brand: 'John Deere', series: 'Serie S', model: 'S790', machineType: 'harvester', engineBrand: 'John Deere', engineModel: 'PowerTech PSS 6135', enginePower: '543 hp', engineDisplacement: '13.5L', transmissionType: 'Hydrostática ProDrive', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    // ── CASE IH HARVESTERS ──
    { brand: 'Case IH', series: 'Axial-Flow', model: 'Axial-Flow 7250', machineType: 'harvester', engineBrand: 'FPT', engineModel: 'Cursor 9', enginePower: '400 hp', engineDisplacement: '8.7L', transmissionType: 'Hydrostática', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    { brand: 'Case IH', series: 'Axial-Flow', model: 'Axial-Flow 9250', machineType: 'harvester', engineBrand: 'FPT', engineModel: 'Cursor 13', enginePower: '592 hp', engineDisplacement: '12.9L', transmissionType: 'Hydrostática', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    // ── NEW HOLLAND HARVESTERS ──
    { brand: 'New Holland', series: 'CR', model: 'CR7.90', machineType: 'harvester', engineBrand: 'FPT', engineModel: 'Cursor 9', enginePower: '396 hp', engineDisplacement: '8.7L', transmissionType: 'Hydrostática', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    { brand: 'New Holland', series: 'CR', model: 'CR9.90', machineType: 'harvester', engineBrand: 'FPT', engineModel: 'Cursor 13', enginePower: '571 hp', engineDisplacement: '12.9L', transmissionType: 'Hydrostática', fuelType: 'Diésel', hydraulicSystem: 'Circuito cerrado de alto flujo', maintenanceIntervals: { oilChange: 250, filters: 250, majorService: 500 } },
    // ── SEEDERS ──
    { brand: 'John Deere', series: '1700', model: '1775NT', machineType: 'seeder', engineBrand: null, engineModel: null, enginePower: null, engineDisplacement: null, transmissionType: null, fuelType: null, hydraulicSystem: 'Accionamiento hidráulico desde tractor', maintenanceIntervals: { lubrication: 50, generalService: 200 }, specs: { rows: 24, rowSpacing: '52.5 cm' } },
    { brand: 'John Deere', series: 'DB', model: 'DB60', machineType: 'seeder', engineBrand: null, engineModel: null, enginePower: null, engineDisplacement: null, transmissionType: null, fuelType: null, hydraulicSystem: 'Accionamiento hidráulico desde tractor', maintenanceIntervals: { lubrication: 50, generalService: 200 }, specs: { rows: 36, rowSpacing: '52.5 cm' } },
    { brand: 'Crucianelli', series: 'Gringa', model: 'Gringa IV', machineType: 'seeder', engineBrand: null, engineModel: null, enginePower: null, engineDisplacement: null, transmissionType: null, fuelType: null, hydraulicSystem: 'Accionamiento hidráulico desde tractor', maintenanceIntervals: { lubrication: 50, generalService: 200 }, specs: { rows: 'variable' } },
  ];

  const result = await prisma.machineTemplate.createMany({ data: templates, skipDuplicates: true });
  console.log(`Seeded ${result.count} machine templates`);
}

main().then(() => prisma.$disconnect()).catch(e => { console.error(e); prisma.$disconnect(); process.exit(1); });
